### ISSUE TITLE
搭建自己的音乐库

### ISSUE THREAD

**Issue by hanxi** [hanxi/blog#47]
> 大家都知道现在音乐版权问题，想听几首歌还要下载各个音乐APP，所以就有下面这个办法。

1. 使用 [jellyfin ](https://jellyfin.org/) 搭建在线听歌平台
2. 使用 [AriaNg](https://github.com/hanxi/AriaNg) 音乐搜索插件下载音乐

jellyfin 和 AriaNg 都可以采用 Docker 安装。

其中 AriaNg 用到了 [QQMusicApi](https://jsososo.github.io/QQMusicApi/) 和 [MiguMusicApi](https://jsososo.github.io/MiguMusicApi/#/) 作为后台接口，可以自己搭建后台或者直接配置反向代理这两个 Api 的测试地址。

效果图

![深度截图_选择区域_20200326223413](https://user-images.githubusercontent.com/1185757/77658644-f051ab00-6fb1-11ea-80b7-e20653886e4f.png)

jellyfin 作为音乐播放器有一段时间了，用起来也不错，我的 docker-compose 配置如下，主要是把开放端口和挂载目录。

```yml
version: '2'

services:
    jellyfin:
        image: jellyfin/jellyfin
        restart: always
        container_name: jellyfin
        network_mode: bridge
        ports:
            - "8096:8096"
            - "8920:8920"
        volumes:
            - ./conf/jellyfin/config:/config
            - ./conf/jellyfin/cache:/cache
            - ./data/files/music:/music
            - ./data/files/download:/media
```

开个 caddy 反向代理接口（如果用Nginx可以自行网上搜教程如何反代）， Caddyfile 如下：

```
{$DOMAIN}/qq {
  log stdout
  proxy / https://api.qq.jsososo.com {
    header_downstream Access-Control-Allow-Origin "*"
  }
}

{$DOMAIN}/migu {
  log stdout
  proxy / http://api.migu.jsososo.com {
    header_downstream Access-Control-Allow-Origin "*"
  }
}
```

aria2 可以参考这个 https://github.com/hanxi/aria2-ariang-docker
